### ISSUE TITLE
an error when run the mif file

### ISSUE THREAD

**Issue by longlong-zhang** [davidcortesortuno/paper-2019_resonant_xray_imaging_confined_magnetic_skyrmion_tubes#1]
when i run the mif2.2 file by the control panel of OOMMF just as  run the miif 2.1 fille.i got an error report.
![选区_006](https://user-images.githubusercontent.com/50805242/72879453-dbe5fd80-3d37-11ea-84d3-8175baf9db11.png)

So is there anything wrong? hoping for your advice

**Comment by davidcortesortuno** [comment]
Hi, you need to create a folder named `field_sweep` before running the `mif` file. That's where the `omf` files are going to be saved. This should be automatically done in the `.sh` file (you can check its content)

**Comment by longlong-zhang** [comment]
Hi,professor davidcortesortuno ,thanks for your reply.after i followed you suggestion ,it worked  well.
